"""18 FMO-family sequences for the fmo18 pipeline run.

Order preserved from the user's FASTA input.
"""

SEQUENCES = []

SEQUENCES.append(("F5SYD3",
    "MATRIAILGAGPSGMAQLRAFQSAQEKGAEIPELVCFEKQADWGGQWNYTWRTGLDENGEP"
    "VHSSMYRYLWSNGPKECLEFADYTFDEHFGKPIASYPPREVLWDYIKGRVEKAGVRKYIRF"
    "NTAVRHVEFNEDSQTFTVTVQDHTTDTIYSEEFDYVVCCTGHFSTPYVPEFEGFEKFGGRI"
    "LHAHDFRDALEFKDKTVLLVGSSYSAEDIGSQCYKYGAKKLISCYRTAPMGYKWPENWDER"
    "PNLVRVDTENAYFADGSSEKVDAIILCTGYIHHFPFLNDDLRLVTNNRLWPLNLYKGVVWE"
    "DNPKFFYIGMQDQWYSFNMFDAQAWYARDVIMGRLPLPSKEEMKADSMAWREKELTLVTAE"
    "EMYTYQGDYIQNLIDMTDYPSFDIPATNKTFLEWKHHKKENIMTFRDHSYRSLMTGTMAPK"
    "HHTPWIDALDDSLEAYLSDKSEIPVAKEA"))

SEQUENCES.append(("A0A410H4M7",
    "MTKRVAIIGAGPSGLAQLRAFQSAQSKGADIPELVCFEKQSDWGGLWNYTWRTGLDENGEP"
    "VHCSMYRYLWSNGPKECLEFADYTFDEHFGKPIASYPPREVLWDYIKGRVEKAGVRDYIRF"
    "NTVVRNVSYDDASETFTVTVQDHNEDKIYSEEFDYVISASGHFSTPKVPEFEGFQTFGGRI"
    "LHAHDFRDALEFKDKDILLVGASYSAEDIGSQCYKYGAKSITTCFRSAPMGYKWPENWEER"
    "PLLERVDTHRAYFADGSSKKIDAIILCTGYLHHFPYLPDSLRLVTDNRLWPLDLYKGVVWE"
    "DNPKFFYLGMQDQWYTFNMFDAQAWYVRDIILGRIPLPSKAEMTQNSQAWREKELKLETAE"
    "EMYTFQGDYIQELIDATDYPSFDIPAVNQTFLEWKHHKKENIMTFRDHSYRSLMTGTMSPK"
    "HHTPWIDALDDSLEAYLADGPQDEKLASNQ"))

SEQUENCES.append(("A0A2N7TXS4",
    "MTKRVAIIGAGPSGLAQLRAFQSARAKGAEIPELVCYEKQADWGGLWNYTWRTGLDENGEA"
    "VHCSMYRYLWSNGPKECLEFADYTFEEHFGKPIASYPPRAVLWDYIQGRVEKMGVRDYIRF"
    "NCPVRQVLYCEQSGKFTVTAHDHTSDTVSSEEFDHVVVASGHFSTPNVPQFEGFETFGGRI"
    "LHAHDFRDALEFKGKDILLVGSSYSAEDIGSQCYKYGARSVTTSYRTRPMGFKWPENWEEK"
    "PLLVRADRDRVHFSDGTSKKADAIILCTGYLHHFPFLSEPLRLKTGNRLWPLGLYQGVVWE"
    "DNPKFFYLGMQDQWYTFNMFDAQAWYVRDVILGRIGVPEKADMRRSSGEWRMREEALETDE"
    "EMIVFQGDYVRSLIAETDYPSFDIDGVNRTFLEWEHHKHDDIMTFRDHSYRSLMTGKLSPP"
    "HHTPWLEAMDDSLEAYLAGPATVMSRAG"))

SEQUENCES.append(("A0A1H9WML5",
    "MRVAIIGAGPSGLAQLRAFQSAQEKGCEIPELVCYEKQADWGGLWNYTWRTGLDQHGEPVH"
    "GSMYRYLWSNGPKECLEFADYTFEEHFGKPIASYPPREVLWDYIKGRVEKADVRRYIRFNC"
    "PVRQITFNEDSEQFTVVAYDHESDVVTTELYDHVIVASGHFSTPNVPDFDGFDRFSGRILH"
    "AHDFRDALEFRGQDVLLVGSSYSAEDIGSQCYKYGARSITTSYRTRPMGFAFPDNWEEKPL"
    "LLKVDGNTAYFKDGTSRRVDAIILCTGYLHHFPFLDESLRLKTSNRLWPLNLYQGVVWENN"
    "PKLFYLGMQDQWYTFNMFDAQAWYARDVLLGRIALPDQAAMQRDSQAWRDREETLDTDESM"
    "IVFQGDYVRTLIDQTDYPSFDIDGVNKTFFMWEEHKHEDLMSFRDYSYRSLMTGTVAPRHH"
    "TRWLEAIDDSLEAYLTAPDEQSTPAPARQPVKAI"))

SEQUENCES.append(("D5KM67",
    "MKKRVAVIGAGPSGTAVLRAFQSAAAKGAEIPEVVCYEKQEDWGGLWNYTWRTGLDEFGEP"
    "VHGSMYRYLWSNGPKEALEFADYTFEEHFGRPIASYPPRAVLWDYIKGRVEKAGVRNWVRF"
    "RTPVRRVDYSDATGKFTVTGHDLKNDHFSTEEFDHVIVASGHFSVPNVPEFPGFRTFNGRI"
    "MHSHDFRDALEFKGKDILIIGRSYSAEDIGSQCYKYGAKSITTSYRSKPMGFKWPANWEEK"
    "PLLQKVENKTAFFKDGTTKEIDAIILCTGYQHTFPFLPDDLRLKTANRLWPLDLYRGVVWE"
    "KNPKLHFIGMQDQFYTFNMFDAQAWYSRDVILGRQQLPSLAEMQKNSAEWRAREETLEDAE"
    "QMIWFQGDYVKELIGLTDYPTFDIEAVNKIFMEWEHHKAEDIMGFRNNSYRSVMTGTLSPK"
    "HHTPWLQAMDDSLESYLGQK"))

SEQUENCES.append(("A0A1I2PX55",
    "MTQRVAIIGAGPSGLAQLRAFQSAQSKGDDIPELVCFEKQDDWGGLWNYTWRTGLDEHGEP"
    "VHGSMYRYLWSNGPKECLEFADYSFDEHFGKPIASYPPREVLWDYIKGRVEKAGVRDYIRF"
    "STPVRNVSYDDTTKKFTVTVHDHINDRIYSEEFDYVITASGHFSTPRVPTFEGFSTFGGRI"
    "LHAHDFRDALEFKDKDILLVGSSYSAEDIGSQCYKYGARSLTSCYRTAPMGFKWPENWEEK"
    "PLLQRVDSNTAYFADGSSKKIDAIILCTGYLHHFPFLPESLCLKTDNRLWPLDLYKGVVWE"
    "DNPQMFYLGMQDQWYTFNMFDAQAWYVRDIIMGKIKLPASKETMTQNTLEWREKELKLKTA"
    "EEMFTFQGDYILELIEATDYPTFDIEGVRKTFLEWKHHKKENIMTFRDYSYRSLMTGTMSP"
    "PHHTPWIDALDDSLDAYLADEPIQKAG"))

SEQUENCES.append(("A0A450UWB6",
    "MTRIAIIGAGPSGLAQLRAFQSAREKGADVPEIVCFEKQADWGGLWNYTWRTGTDEYGEPI"
    "HCSMYRYLWSNGPKECLEFADYTFEEHFGKPIASYPPRAVLWDYIKGRVEKAGVRHWIRFR"
    "TPVRQVVYSEETGRFTVTVHDLPQDGTYSEEFDYVVVASGHFSTPNVPDFQGLDTFNGRVL"
    "HAHDFRDAREFAGKDILIVGASYSAEDIGSQCYKYGAKSITCSYRTAPMGFHWPDNWEEVP"
    "LLARAEKDTCYFKDGSNKKIDAIILCTGYLHHFPFLPDGLRLKTNNRLWPPGLYQGIFWEP"
    "NPRLIYLGMQDQFYTFNMFDAQAWYARDYILGRIDLPSKEEMARHSQSWRNREEGLENDEQ"
    "MIVFQGDYVKELIAGTDYPDFDIDGVNRTFMEWERHKHEDIMGFRDNAYRSLMTGALSPPH"
    "HTRWLEAMDDSLESYLNDPRKGAK"))

SEQUENCES.append(("A0A3N8KYV3",
    "MTQRVAIIGAGPSGMAQLRAFQSAQAKGADIPQLVCFEKQRDWGGMWNYTWRTGTDEFGEP"
    "VHGSMYRYLWSNGPKECLEFADYTFEEHFGKPIASYPPREVLWDYIKGRVEKAGVRPYIRF"
    "GTVVRQIAFDDASGRFTVTVHDLDKDVVYAEDFDYVVNACGHFSTPNLPSFPGFDSFGGRI"
    "LHAHDFRDALEFKDKDILLVGSSYSAEDIGSQCYKYGARSITSCYRTAPMGYHWPANWEEK"
    "PLLERVRGNVAFFADGTSKKIDAIILCTGYQHHFPFLPDSLRLKTNNRLWPLDLYKGIFWE"
    "RNPKLIYLGMQDLWYSFNMFDAQAWYARDVILGRIALPGFDAMHADSLAWRAREESLVTNQ"
    "QMFEYQGSYIQDLIDATDYPNFDIAGVNRTFLAWKHDKHEDIMGYRDKSYRSLMTGTQSPP"
    "HHTPWLDALDDSMDAYLGERAPEPRVRAG"))

SEQUENCES.append(("A0A1T5GXM2",
    "MSEHVSTKILIVGSGANAISPAVKLALRGETDFRMITKDSDFGGVWHVNRYPGCITDIHVA"
    "AYQFSYEISGEWTSSHPEAREMAAYLRKVARHYGLYDHVDFNTELLGAEWDKNGLYWKVTT"
    "NAVTYHARFLILCTGFLEQLKFPELGGTEKFKGRLFHSVHWPEGYTGEGDRIAVLGTSASG"
    "VQIVPEMQKVADHVFVFQRTPMHLLPLNREVYSPDELARRRSDPDFLVKERDEKLAMFDKV"
    "AYDALFNSETPQQVAERQALIDAHRERLVPDPDLREKLTPKYLLGCKRPTRTDLFYPSLQQ"
    "PNVTLIAEGAVALEEDTIISSSGQAFEVDAVVMATGFYWGGDILNRIRRRDGRTVAEHQAG"
    "HRRAHKSVSLSGCPNLFLVGGAGANGAVWNGYAPGELVPEYIFAVLDYMKDNGIEAFEVRE"
    "ECETEWKARTDEILSKAAIVVGGCVNYMLDESGHDMSSWPGTMRDMERAMQNFEPDHYQPI"
    "GAGS"))

SEQUENCES.append(("A0A4D4JGR6",
    "MGTPRTRETDVLIIGGGFAGLGMAIELKRSGRNDFVLLEKAEDVGGTWRDNTYPGCACDIH"
    "SHMYSFSFELNPGWSRMFARQPEIWEYLRRVTDKYGLRRHIRFGAEVTGAHWDERNRVWRV"
    "RTRAGDTYTARAVVSGVGALHVPNVPKLPGAERFRGTAFHSANWDHDYDLRGRRVAVIGTG"
    "ASAIQFVPEIARDVAELHIFQRTPPWIVPKMDRPVRPWEQRMFRLLPLTQRLYRNAIYWML"
    "ESRAVGFTINPKLMGLAQTIARKHLEKQVPDPDLRAKLTPNYTMGCKRVLISNDYYPTLAQ"
    "PHVHLVTDGVAEITEDAVVDGAGMAHEVDAIIYGTGFHVTDGYDHLDIVGRDGRNLVQQWH"
    "SEGMETYLGIAVSGFPNFFFLLGPNTGLGHNSVVFMIESQIHYIGQCLRLLDTHGATAMDV"
    "RARAQSTFYRDLQRQLTKGVWTQGGCNSWYLDAHGVNRTIWPGFTWRYWQRTRKVRLADFE"
    "LLSAGRPEPDRELAESVG"))

SEQUENCES.append(("A0A7V9IXK9",
    "MVEQLPGRVDVAIVGAGFGGLGMAIQLERQALRDFVVLERGTDVGGAWHANTYPGAQCDIP"
    "SSLYSFSFAPKLDWTRAYPEQKEIQGYLRGCVERFGIGDRIHLETELQDAAWDGNRRRWRI"
    "ETSAGPLEARVLVAAPGLLSEPSTPALSGLERFEGRTFHTATWDHSHDLTDRDVAVIGTGA"
    "TGVQVVPRIRNRVRRLTVFQRTPPWVIPHVDREVTMIARRLYHLAPPLQRLVRGLVYAFNE"
    "HFVLGMSYWPRLLKAHELYARLHMRRQVPDPDLRRRLTPDYSFGCKRILLSSDWYPSFEAP"
    "NVELVTSGVEEVRERSVVAFDGTEHPADTLVFATGFVPTDPPIARRLRGSEGRTLSEAWGG"
    "SPQAYLATAVAGFPNLFLLYGPNSNLGHSSIVYMLESQVRYVMGALKAMRERGHEALEVRR"
    "EVQDAYNEELQRRLARSVWDSGGCGSWYLDANGRDSTQWPGFTLEFRLRTRAFDLDSYSEP"
    "PVTSRMPSTTLSGSSNVGM"))

SEQUENCES.append(("A0A132NIF8",
    "MNDQQRAGDPAVVIVGAGFAGLGMAIQLKRAGVEDFVVLEKADEVGGTWRDNRYPGCACDV"
    "QSHLYSYSFEPNPAWSRMFAEQQEIWDYLKHCAEKYRITPHIRFGTELVGAEYDDATGTWR"
    "VRTNRGAITTRALVLATGPLHQPAYPDIPGIDRFRGKAFHSAEWDHGYDLAGKRVAVIGTG"
    "ASAIQFVPRIAPRVDRLHLFQRTPPWILPKPDRSISPLEQRLFRAVPALQRLYRSAIYWTL"
    "EARILGFTVHPRLMKLAEAVARQHLRRQVPDPELRRKLTPDYTIGCKRILISNDYYPALTR"
    "PNVELVTDGIAEIREHAVVTRDGVERPVDAIIYGTGFHVIDAFDHLDIVGRDGLKLREAWS"
    "GGVEAYLGVTVAGFPNLFFLLGPNSGLGHSSMVFMIEAQVRYVLQALRPLLRGDARAVDVR"
    "ADVQATFNQRLQARLREAVWGIGGCRSWYLDENGVNRALWPGSTAEYWLRTRRLKPAEYRI"
    "EA"))

SEQUENCES.append(("A0A1H5B1B3",
    "MDEAIVKHTKMLVVGSGGNAIALAVSLIRAGYSDLGIITKHHDFGGAWLQNTYPGCEVDCK"
    "SAAYQFSFDLNADWSALYATQPELKNYLQKVARDGGLYERTIFNCAMTNARWDETRAHWIV"
    "GTTCGSMAADHLLLATGFLEEAVTPDLPGFDSFRGASFHSSRWPAGYTGKGERIAVLGSGS"
    "SAAQIVPAMQETADHVYQFQRTPTWMLPKGNRALSAEEKQALRSDPAELQKQRDEVIEMQE"
    "TAWNDVFVGSNSAFYLEISQKFLADEVPDPVLRAHLTPDHALGCKRPVISDNYYRSLGNPN"
    "VTLVPEGVTRIEDGRLVTASGREFEVDTIVLATGFYFGGHILDLVQRRDGQSVGSFQAGHP"
    "RAYKAISVAGCPNLYLVGGPAPNGQIWNGLYPGEGVAAYVIRVMEYLQAHDLRAVEVTHEA"
    "EIAWKAATDEILDKSPVVAGGCVNYAQDSKGHNKATWPGNLASMTMAMSHFEASDYHAIRG"
    "LP"))

SEQUENCES.append(("A0A063Y6V3",
    "MNTRVAIIGAGPCGLAQLRAFQSAAAKGAAIPELVCFEKQSDWGGMWNYTWRTGVDEHGEP"
    "VHGSMYRYLWSNGPKECLEFADYTFDEHFGRPIGSYPPREVLWDYIKGRVEKAGVRDYIRF"
    "NTAVRQVSYDETSGLFSVTVQDHSNNRVYTETFDYVVNACGHFSTPNTPYFEGFERFGGRV"
    "LHAHDFRDALEFKDKDILVVGSSYSAEDIGSQCYKYGARSITSCYRSAPMGYQWPQNWEEK"
    "PLLQRVDSDTAWFADGSHKRIDAIILCTGYQHHFPFLPDSLRLITENRLWPLKLYKGIFWE"
    "DNPKFLYLGMQDQWYSFNMFDAQAWYARDVILGRISLPGKAEMQAENQAWREREEKLQTAQ"
    "EMFEFQGSYIQHLIDATDYPSFDIQAVNETFLAWKHDKYEDIMGYRNKCYRSLMTGTLATP"
    "HHTPWLDALDDSLEAYLQETPRLKSAV"))

SEQUENCES.append(("A0A5K7Y5X3",
    "MTKRIAIIGAGPSGLAQLRAFQSAADKGIDIPEIVCYEKQSDWGGLWNYSWRTGLDQNGEP"
    "VHGSMYRYLWSNGPKECLEFADYSFEEHFGHPIASYPPRAVVFDYIKGRVEKAGVRKYIRF"
    "NCPVRHVSFDDTREQFTLSVHDLQADAVVQEQFDHVIVASGHFSTPNVPEFPGFSQFNGRI"
    "LHAHDFRDALEFKGKDLLLIGSSYSAEDIGSQCYKYGARSITTSYRTAPMGFAWPDNWEEK"
    "PLLLKVDRDTAYFRDGTSKKIDAIILCTGYLHHFPFLDEPLRLKTGNRMWPLGLYKGAAWE"
    "ANPRLFYLGMQDQWYTFNMFDAQAWWVRDVILGEIALPSREAMQADSQSWRDREETLDSDE"
    "SMILFQGDYVKSLISETDYPSFDIDGVNRTFLEWEHHKHENIMTFRDHSYRSLMTGTLAPP"
    "HHTPWLDAMDDSLEAFLAQPDKSARQTGDDRATTAQLTTDDA"))

SEQUENCES.append(("L0KQ21",
    "MNTRVAVIGAGPSGLAQLRAFKSAADKGAEIPEIVCFEKQSDWGGLWNYTWRTGLDEHGDP"
    "VHGSMYRYLWSNGPKECLEFADYTFEEHFGRPIGSYPPRAVLWDYIKGRVEKSGLRKWVRF"
    "NSPVRMVTFSDETKKFTVTAHDRSNDVTYSEEFDNVVVASGHFSVPNVPYFEGFSTFNGRI"
    "LHSHDFRDAMEFKGKDILIIGRSYSAEDIGSQCYKYGAKSITSSYRSKPMGFKWPENWKEV"
    "PLLQKVVGKTAHFKDGTTKDVDAIILCTGYLHSFPFLTDDLKLKTANRMWPLDLYEGVVWE"
    "KNPKLSYIGMQDQFYTFNMFDAQAWFARDVIMGRIRLPSAEAMAAHGAKWRAREETLEDAE"
    "QMIWFQGDYTKELMDQTDYPGFDVEAVNQTFMEWEHHKAEDIMSFRDHSYRSLMTGTMAPL"
    "HHTPWLQALDDSMESYLEVKGVAAE"))

SEQUENCES.append(("A0A191YSB4",
    "MTTRVAIIGAGPCGMAQLRAFQSTRDQGTPIPELVCYEKQQDWGGMWNYTWRTGLDEHGEP"
    "VHGSMYRYLWSNGPKECLEFADYTFEEHFGRPIGSYPPREVLWDYIKGRVEKAGVRDYIRF"
    "NNVVRQVTFDEETRRFTVVAHDHGSDTRTSEEFDYVINACGHFSTPKLPYFPGFEQFGGRI"
    "LHAHDFREALEFKGKDLLIVGSSYSAEDIGSQCYKYGARSITSCYRTAPMGYDWPANWEEK"
    "PLLQRLEKNRAYFIDGTHKHIDAVILCTGYKHHFPFLPDELCLKTDNRLWPMNLYKGIFWE"
    "PNPQLIYLGMQDQWYSFNMFDAQAWYARDVILGRIQLPSQAEMIADSLQWHTREQTLETNQ"
    "QMFEFQGAYIQQLVDATDYPNFDIAAVNDTFLHWKHDKAHDIMGYRDKSYRSLMTGTQSPP"
    "HHTPWLHALDDSMAAYLAGPPMSVKSIG"))

SEQUENCES.append(("A0A367WN69",
    "MTLRVAIIGAGPSGMAQMRAFQSAAAKGAEIPEIVCFERQEDWGGLWNYTWRTGLDEYGEP"
    "IHGSMYRYLWSNGPKECLEFADYTFEEHFGKPIASYPPRAVIWDYIKGRVEKANVRPWVRF"
    "RTPVRSVEFDEESQTFLVTAHDLKNDVVSTEEFDYVIVANGHFSTPNVPEFPGFETFGGRV"
    "LHAHDFRDALEFKDKDILIIGTSYSAEDIGSQCYKYGCKSVTVSHRTNPIGFDWPDNWAEV"
    "PLLTKVEGNTAWFKDGSSRDVDAIILCTGYQHHFPFLTDDLRLKTANRLWPLGLYNGVVWE"
    "ENPRLMYLGMQDQFYTFNMFDAQAWYARDVIMGRLDLPSRDEMKADSQAWRDREEGLKDDH"
    "DMIWFQGDYTAHLIEMTDYPMFDIEGVNKTFEEWEHDKAHDIMGYRNKSYRSLMTGNMSPA"
    "HHTPWLDELDDSLEAYLQTGLKSSAAE"))
