name: filterpipeline2
channels:
  - conda-forge
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
  - pytorch
  - bioconda
dependencies:
  - python=3.11
  - pyarrow
  - pdbfixer
  - foldseek
  - mmseqs2
  - biotite
  - openbabel
  - openmm==8.3.1
  - fpocket
  - pip
  - plip
  # - pip:
  #   - enzymetk
  #   - filterzyme
  #   - rdkit
  #   - freesasa
  #   - docko
  #   - chai_lab
  #   - squidly  # catalytic-residue prediction CLI; requires GPU for ESM2 inference


#   import sys
# from docko.boltz import *

# base_dir = ''
# run_boltz('boltzproteinexample', 
#          'MSIEKIPGYTYGKTESMSPLNLEDLKLLKDSVMFTEEDEKYLKKAGEVLEDQVEEILDTWYGFVGSHPHLLYYFTSPDGTPNEEYLAAVRKRFSKWILDTCNRNYDQAWLDYQYEIGLRHHRTKKNRTDNVESVPNINYRYLVAFIYPITATIKPFLARKGHTSEEVEKMHQAWFKATVLQVALWSYPYVKQGDF', 
#          'CCCCC(CC)COC(=O)C1=CC=CC=C1C(=O)OCC(CC)CCCC',
#          base_dir
#         )