# structurezyme/hosts.yml
default:
  output_root: /mnt/labs/data/mora/structurezyme_runs
  boltz_cache_dir: /mnt/labs/data/mora/boltz_cache
  squidly_weights_dir: /mnt/labs/data/mora/squidly_weights
  placer_env_path: /mnt/labs/data/mora/software/PLACER/env
